name: Sidelobe Build Matrix Linux
on:
  workflow_call:
jobs:
  build:
    name: Linux, ${{matrix.cxx}}, ${{matrix.tinywav_options}}, ${{matrix.build_type}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-9
          - g++-11
        build_type: [Debug, Release]
        std: [14]
        tinywav_options: [ALLOCA, MALLOC, VLA]
        include:
          - cxx: g++-9
            cc: gcc-9
            other_pkgs: g++-9 gcc-9
          - cxx: g++-11
            cc: gcc-11
            other_pkgs: g++-11 gcc-11
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        lfs: 'true'
    - name: Install Toolchain
      run: sudo apt-get install -y ${{matrix.other_pkgs}}
    - name: Setup & Cmake
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DTINYWAV_ALLOCATION=${{matrix.tinywav_options}} \
              ..
        
    - name: Build & Run Tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: build
      run: |
        cmake --build . --parallel 2
        ctest -C ${{ matrix.build_type }} -L TinywavTest -j 2
